version: "2.1"
services:
  fleet_watch_db:
    image: postgres:9.6
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: fleet_watch
      POSTGRES_USER: fleet_watch
      POSTGRES_PASSWORD: knlzlEI90kMc
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  fleet_watch_backend:
    image: fleet_watch
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - fleet_watch_db
    environment:
      - DB_CONN_STR=postgresql+psycopg2:://fleet_watch:knlzlEI90kMc@fleet_watch_db:5433/fleet_watch
      - FLASK_ENV=development
      - FLASK_APP=fleet_watch_app.py
      - LISTEN_PORT=5000
    volumes:
      - ./api:/app
    ports:
      - "5000:5000"
      - "443:443"

  fleet_watch_frontend:
    build:
      context: .
      dockerfile: ui/Dockerfile
    depends_on:
      - fleet_watch_db
      - fleet_watch_backend
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - 3000:3000