version: "2.1"
services:
  fleet_watch_db:
    image: postgres:9.6
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: fleet_watch
      POSTGRES_USER: fleet_watch
      POSTGRES_PASSWORD: knlzlEI90kMc
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  fleet_watch_backend:
    image: fleet_watch
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    depends_on:
      - fleet_watch_db
    environment:
      - DB_CONN_STR=postgresql+psycopg2:://fleet_watch:knlzlEI90kMc@fleet_watch_db:5433/fleet_watch
      - FLASK_ENV=development
      - FLASK_APP=fleet_watch_app.py
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
      - "443:443"
    command:
      - "bash"

  fleet_watch_frontend:
    image: node:11-alpine
    working_dir: /root
    restart: "no"
    depends_on:
      - fleet_watch_db
      - fleet_watch_backend
    volumes:
      - ./ui:/root
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    command:
      - "/bin/sh"
